# Assignment 2 – E-Commerce Sales Analysis

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_excel('ecommerce_orders_raw.xlsx')
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895,4.0
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526,1.0
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613,4.0
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.380,3.0
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.273,5.0

## Part A – Data Understanding

In [2]:
# Q1 Load the dataset
df

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895,4.0
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526,1.0
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613,4.0
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.380,3.0
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.273,5.0
...,...,...,...,...,...,...,...,...,...,...,...
15095,O005192,C02154,Bangalore,Clothing,Jeans,5,34504.40,10,Net Banking,2025-07-19 08:20:40.403,5.0
15096,O013419,C02986,Hyderabad,Electronics,Smartphone,1,79634.65,0,Net Banking,2026-05-31 06:51:11.725,4.0
15097,O005391,C00104,Pune,Electronics,Headphones,5,12912.20,10,Cash on Delivery,2025-07-26 23:45:18.661,2.0
15098,O000861,C01970,Bangalore,Beauty,Perfume,2,8755.21,10,Net Banking,2025-02-03 00:37:43.831,4.0
15099,O007271,C02352,Kolkata,Home Appliances,Vacuum Cleaner,2,72517.78,5,Debit Card,2025-10-07 04:28:43.315,4.0

In [3]:
# Q2 Display structure and dimensions
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15100 entries, 0 to 15099
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          15100 non-null  object
 1   Customer_ID       15100 non-null  object
 2   City              15100 non-null  object
 3   Product_Category  15100 non-null  object
 4   Product           15100 non-null  object
 5   Quantity          15100 non-null  int64
 6   Unit_Price        15100 non-null  float64
 7   Discount          15100 non-null  int64
 8   Payment_Method    15100 non-null  object
 9   Order_Date        15100 non-null  datetime64[ns]
 10  Rating            14699 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 1.3+ MB
None
(15100, 11)

In [4]:
# Q3 Data types of all columns
df.dtypes

Order_ID                    object
Customer_ID                 object
City                        object
Product_Category            object
Product                     object
Quantity                     int64
Unit_Price                 float64
Discount                     int64
Payment_Method              object
Order_Date          datetime64[ns]
Rating                     float64
dtype: object

In [5]:
# Q4 Identify missing values
df.isnull().sum()

Order_ID              0
Customer_ID           0
City                  0
Product_Category      0
Product               0
Quantity              0
Unit_Price            0
Discount              0
Payment_Method        0
Order_Date            0
Rating              401
dtype: int64

In [6]:
# Q5 Identify duplicate orders
df[df.duplicated()]

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
804,O002217,C01672,Chennai,Books,Self Help,5,37140.96,20,Credit Card,2025-03-27 02:24:06.336,NaN
921,O001374,C00342,Delhi,Books,Novel,3,49786.14,20,Credit Card,2025-02-22 17:26:28.186,4.0
988,O002679,C02462,Pune,Books,Self Help,2,67215.23,10,Cash on Delivery,2025-04-13 20:12:33.650,3.0
1046,O002627,C02398,Delhi,Home Appliances,Air Purifier,3,74694.80,15,Credit Card,2025-04-11 20:16:58.628,5.0
1198,O014868,C00909,Kolkata,Home Appliances,Air Purifier,1,70777.03,25,Credit Card,2026-07-25 22:20:26.482,5.0
...,...,...,...,...,...,...,...,...,...,...,...
14630,O010505,C00257,Coimbatore,Beauty,Skin Serum,4,95997.99,25,UPI,2026-02-08 09:07:54.512,3.0
14687,O007418,C02780,Chennai,Beauty,Perfume,2,44950.38,15,Credit Card,2025-10-12 19:57:46.551,3.0
14769,O002761,C02646,Bangalore,Sports,Cricket Bat,5,12533.09,5,Credit Card,2025-04-16 23:47:08.109,4.0
14883,O013168,C00217,Kolkata,Beauty,Skin Serum,1,24620.22,20,Credit Card,2026-05-21 15:30:58.444,4.0
14884,O002849,C01284,Hyderabad,Books,Biography,1,77205.47,15,Cash on Delivery,2025-04-20 08:53:30.454,4.0

In [7]:
# Q6 Unique values
print("City:", df['City'].unique())
print("Product Category:", df['Product_Category'].unique())
print("Payment Method:", df['Payment_Method'].unique())

City: ['Delhi' 'Pune' 'Hyderabad' 'Mumbai' 'Kolkata' 'Bangalore' ' chennai '
 'Chennai' 'Coimbatore' 'CHENNAI']
Product Category: ['Home Appliances' 'Books' 'Beauty' 'Sports' 'Clothing' 'Electronics']
Payment Method: ['Debit Card' 'Net Banking' 'UPI' 'Credit Card' 'Cash on Delivery']

## Part B – Data Cleaning

In [8]:
# Q7 Handle missing ratings
df['Rating'] = df['Rating'].fillna(df['Rating'].median())
df['Rating'].isnull().sum()

0

In [9]:
# Q8 Standardize city names
df['City'] = df['City'].astype(str).str.strip().str.title()
df['City'].unique()[:10]

array(['Delhi', 'Pune', 'Hyderabad', 'Mumbai', 'Kolkata', 'Bangalore',
       'Chennai', 'Coimbatore'], dtype=object)

In [10]:
# Q9 Identify invalid quantities
df[df['Quantity'] <= 0]

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
101,O012623,C02458,Delhi,Home Appliances,Vacuum Cleaner,-2,17821.53,5,UPI,2026-04-30 17:12:38.691,5.0
476,O004601,C02136,Chennai,Clothing,Jeans,-2,96639.36,20,UPI,2025-06-26 15:38:33.514,4.0
1639,O006694,C01856,Pune,Sports,Football,-2,44119.66,0,Net Banking,2025-09-15 00:40:48.163,4.0
2420,O007460,C02632,Bangalore,Electronics,Smart Watch,-2,68963.12,0,Debit Card,2025-10-14 10:40:21.761,5.0
4496,O002305,C01604,Kolkata,Sports,Cricket Bat,-2,21758.55,25,Net Banking,2025-03-30 11:30:28.682,5.0
4861,O012185,C00664,Chennai,Books,Novel,-2,40781.24,25,UPI,2026-04-13 21:31:22.926,1.0
5008,O001742,C02508,Pune,Books,Self Help,-2,56782.27,20,Net Banking,2025-03-08 20:36:45.267,3.0
6591,O011832,C02379,Hyderabad,Electronics,Smartphone,-2,75507.40,0,Debit Card,2026-03-31 08:10:35.562,5.0
8972,O002382,C00456,Kolkata,Clothing,Shoes,-2,62380.34,25,Debit Card,2025-04-02 10:28:33.234,4.0
9230,O008580,C01669,Kolkata,Clothing,Jacket,-2,14579.25,20,Debit Card,2025-11-26 10:56:00.704,3.0
10292,O014631,C00935,Chennai,Electronics,Smart Watch,-2,49718.06,25,UPI,2026-07-16 19:54:24.938,4.0
11190,O000786,C02143,Chennai,Beauty,Perfume,-2,81535.06,15,UPI,2025-01-31 03:30:15.241,4.0
11382,O014905,C00834,Chennai,Home Appliances,Air Purifier,-2,87016.82,25,Debit Card,2026-07-27 08:26:31.786,5.0
11568,O014858,C00084,Pune,Beauty,Shampoo,-2,31453.49,0,UPI,2026-07-25 13:07:26.670,5.0
11575,O008382,C00602,Mumbai,Home Appliances,Mixer,-2,78817.20,15,Cash on Delivery,2025-11-18 20:26:40.427,4.0
11796,O007711,C00453,Pune,Home Appliances,Microwave,-2,10968.44,20,Credit Card,2025-10-24 02:00:35.042,4.0
11948,O007354,C01105,Chennai,Home Appliances,Microwave,-2,26472.63,0,Net Banking,2025-10-10 08:58:35.754,5.0
14009,O008473,C02162,Bangalore,Electronics,Headphones,-2,25481.18,25,Debit Card,2025-11-22 08:18:56.716,4.0
14757,O000263,C01439,Pune,Books,Biography,-2,17354.40,15,UPI,2025-01-11 01:28:31.074,4.0
14845,O013809,C00770,Delhi,Clothing,Shoes,-2,9723.51,15,UPI,2026-06-15 06:18:04.392,3.0

In [11]:
# Q10 Handle duplicate orders
df = df.drop_duplicates()
df.shape

(15000, 11)

In [12]:
# Q11 Convert Order_Date to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Order_Date'].dtype

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\843999630.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

dtype('<M8[ns]')

## Part C – Feature Engineering

In [13]:
# Q12 Gross_Amount
df['Gross_Amount'] = df['Quantity'] * df['Unit_Price']
df[['Quantity', 'Unit_Price', 'Gross_Amount']].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\16648732.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross_Amount'] = df['Quantity'] * df['Unit_Price']

   Quantity  Unit_Price  Gross_Amount
0         2    10042.08      20084.16
1         1    34791.00      34791.00
2         2    15693.00      31386.00
3         5    72700.86     363504.30
4         5    89712.89     448564.45

In [14]:
# Q13 Discount_Amount
df['Discount_Amount'] = df['Gross_Amount'] * df['Discount'] / 100
df[['Gross_Amount', 'Discount', 'Discount_Amount']].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\3502834242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discount_Amount'] = df['Gross_Amount'] * df['Discount'] / 100

   Gross_Amount  Discount  Discount_Amount
0      20084.16        10        2008.4160
1      34791.00        15        5218.6500
2      31386.00        15        4707.9000
3     363504.30        20       72700.8600
4     448564.45        25      112141.1125

In [15]:
# Q14 Net_Amount
df['Net_Amount'] = df['Gross_Amount'] - df['Discount_Amount']
df[['Gross_Amount', 'Discount_Amount', 'Net_Amount']].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\1725996841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net_Amount'] = df['Gross_Amount'] - df['Discount_Amount']

   Gross_Amount  Discount_Amount   Net_Amount
0      20084.16        2008.4160   18075.7440
1      34791.00        5218.6500   29572.3500
2      31386.00        4707.9000   26678.1000
3     363504.30       72700.8600  290803.4400
4     448564.45      112141.1125  336423.3375

In [16]:
# Q15 Rating_Category
def rating_category(r):
    if r <= 2:
        return 'Poor'
    elif r == 3:
        return 'Average'
    elif r == 4:
        return 'Good'
    else:
        return 'Excellent'

df['Rating_Category'] = df['Rating'].apply(rating_category)
df[['Rating', 'Rating_Category']].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\2550314855.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating_Category'] = df['Rating'].apply(rating_category)

   Rating Rating_Category
0     4.0            Good
1     1.0            Poor
2     4.0            Good
3     3.0         Average
4     5.0       Excellent

In [17]:
# Q16 Extract Year, Month, Day, Day of Week
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Day'] = df['Order_Date'].dt.day
df['Day_of_Week'] = df['Order_Date'].dt.day_name()

df[['Order_Date', 'Year', 'Month', 'Day', 'Day_of_Week']].head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9940\1908795786.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\HP\AppData\Local\Temp\ipykernel_9940\1908795786.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month
C:\Users\HP\AppData\Local\Temp\ipykernel_9940\1908795786.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day'] = df['Order_Date'].dt.day
C:\Users\HP\AppData\Local\Temp\ipykernel_9940\1908795786.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day_of_Week'] = df['Order_Date'].dt.day_name()

               Order_Date  Year  Month  Day Day_of_Week
0 2026-07-25 02:03:50.895  2026      7   25    Saturday
1 2026-06-27 05:51:34.526  2026      6   27    Saturday
2 2026-07-25 15:53:20.613  2026      7   25    Saturday
3 2025-02-03 22:44:55.380  2025      2    3      Monday
4 2025-01-16 18:48:10.273  2025      1   16    Thursday

## Part D – Business Analysis

In [18]:
# Q17 Total revenue
df['Net_Amount'].sum()

1979711486.4074998

In [19]:
# Q18 Total number of orders
df['Order_ID'].nunique() if 'Order_ID' in df.columns else len(df)

15000

In [20]:
# Q19 Average order value
df['Net_Amount'].mean()

131980.76576049998

In [21]:
# Q20 Total revenue by product category
df.groupby('Product_Category')['Net_Amount'].sum()

Product_Category
Beauty             3.307883e+08
Books              3.325953e+08
Clothing           3.451293e+08
Electronics        3.231161e+08
Home Appliances    3.185674e+08
Sports             3.295151e+08
Name: Net_Amount, dtype: float64

In [23]:
# Q21 Top 10 products by revenue
df.groupby('Product')['Net_Amount'].sum().sort_values(ascending=False).head(10)

Product
Jeans         9.337433e+07
Jacket        8.881844e+07
Yoga Mat      8.832334e+07
Self Help     8.825103e+07
Shampoo       8.816100e+07
Skin Serum    8.718235e+07
Laptop        8.697328e+07
Mixer         8.515870e+07
Headphones    8.354481e+07
Textbook      8.347781e+07
Name: Net_Amount, dtype: float64

In [24]:
# Q22 City generating the highest revenue
city_revenue = df.groupby('City')['Net_Amount'].sum()
city_revenue.idxmax(), city_revenue.max()

('Chennai', 284736059.7545)

In [25]:
# Q23 Most frequently used payment method
df['Payment_Method'].value_counts().idxmax()

'Debit Card'

In [26]:
# Q24 Average rating for each product category
df.groupby('Product_Category')['Rating'].mean()

Product_Category
Beauty             3.897772
Books              3.853803
Clothing           3.909233
Electronics        3.833603
Home Appliances    3.854523
Sports             3.883279
Name: Rating, dtype: float64

In [27]:
# Q25 Monthly revenue
df.groupby(['Year', 'Month'])['Net_Amount'].sum()

Year  Month
2025  1        1.077725e+08
      2        9.685231e+07
      3        1.057524e+08
      4        1.072300e+08
      5        1.063948e+08
      6        1.022474e+08
      7        1.074132e+08
      8        1.072570e+08
      9        1.082502e+08
      10       1.084585e+08
      11       1.047789e+08
      12       1.034943e+08
2026  1        1.108373e+08
      2        9.477007e+07
      3        1.012975e+08
      4        9.957132e+07
      5        1.064280e+08
      6        9.940086e+07
      7        1.015050e+08
Name: Net_Amount, dtype: float64

In [28]:
# Q26 Highest-revenue month
monthly = df.groupby(['Year', 'Month'])['Net_Amount'].sum()
monthly.idxmax(), monthly.max()

((2026, 1), 110837307.0425)

In [29]:
# Q27 Top 10 customers by total spending
df.groupby('Customer_ID')['Net_Amount'].sum().sort_values(ascending=False).head(10)

Customer_ID
C01527    2.398928e+06
C02170    2.179011e+06
C01626    2.177252e+06
C01856    2.175716e+06
C01882    2.104829e+06
C00990    2.057789e+06
C02988    2.009290e+06
C02588    2.002666e+06
C00139    1.988373e+06
C00944    1.971527e+06
Name: Net_Amount, dtype: float64

In [30]:
# Q28 Compare revenue generated by different cities
df.groupby('City')['Net_Amount'].sum().sort_values(ascending=False)

City
Chennai       2.847361e+08
Mumbai        2.476805e+08
Coimbatore    2.462794e+08
Delhi         2.462101e+08
Pune          2.435440e+08
Bangalore     2.395935e+08
Kolkata       2.391213e+08
Hyderabad     2.325466e+08
Name: Net_Amount, dtype: float64

In [31]:
# Q29 Product category with highest average order value
avg_order_value = df.groupby('Product_Category')['Net_Amount'].mean()
avg_order_value.idxmax(), avg_order_value.max()

('Clothing', 135027.10187206572)